# Generated by Django 5.2.11 on 2026-02-27 06:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("landing", "0001_initial"),
        ("landing", "0002_contactinquiry_marketing_opt_in"),
        ("landing", "0003_funnelevent"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("company_name", models.CharField(blank=True, max_length=100)),
                ("contact", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("inquiry_type", models.CharField(max_length=20)),
                ("message", models.TextField()),
                (
                    "privacy_agreed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "email_delivery_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("emailed_at", models.DateTimeField(blank=True, null=True)),
                ("email_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("marketing_opt_in", models.BooleanField(default=False)),
                ("marketing_opted_in_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FunnelEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(db_index=True, max_length=80)),
                ("page_key", models.CharField(blank=True, max_length=40)),
                ("lead_source", models.CharField(blank=True, max_length=80)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
