# Generated by Django 5.2.11 on 2026-03-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0005_analyticsexcludedip"),
    ]

    operations = [
        migrations.AddField(
            model_name="funnelevent",
            name="client_ip",
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
    ]
