# Generated by Django 5.2.11 on 2026-04-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0006_funnelevent_client_ip"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("summary", models.TextField(max_length=300)),
                ("body_markdown", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("solo_dev", "1인 개발"),
                            ("mvp", "MVP"),
                            ("outsourcing", "외주"),
                            ("retrospective", "제품 회고"),
                            ("operations", "운영/마케팅"),
                        ],
                        db_index=True,
                        default="solo_dev",
                        max_length=30,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="쉼표로 구분합니다. 예: 1인 개발,MVP,외주",
                        max_length=200,
                    ),
                ),
                ("seo_title", models.CharField(blank=True, max_length=120)),
                ("seo_description", models.CharField(blank=True, max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-published_at"],
                        name="landing_bui_status_de43aa_idx",
                    )
                ],
            },
        ),
    ]
