# Generated by Django 5.2.11 on 2026-04-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0008_seed_first_build_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildnote",
            name="slug",
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
    ]
