# Generated by Codex on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0009_alter_buildnote_slug"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="buildnote",
                    name="slug",
                    field=models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        help_text=(
                            "비워두면 제목으로 자동 생성합니다. 국내 검색 의도가 강한 글은 "
                            "짧은 한글 slug를 써도 됩니다. 예: 1인-개발자-mvp-범위. "
                            "너무 긴 문장형 slug는 공유/분석 URL이 지저분해질 수 있어 피합니다."
                        ),
                        max_length=140,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
