# Generated by Codex on 2026-05-28

from django.db import migrations, models


def add_column(name: str, field_type: str = "varchar(80)") -> migrations.RunSQL:
    return migrations.RunSQL(
        sql=f'ALTER TABLE "landing_contactinquiry" ADD COLUMN "{name}" {field_type} NULL;',
        reverse_sql=f'ALTER TABLE "landing_contactinquiry" DROP COLUMN "{name}";',
    )


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0010_alter_buildnote_slug_unicode"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                add_column("ad_campaign"),
                add_column("ad_group"),
                add_column("ad_intent"),
                add_column("ad_keyword", "varchar(120)"),
                add_column("ad_source", "varchar(40)"),
                add_column("landing_variant"),
                add_column("lead_source"),
                add_column("page_key", "varchar(40)"),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="contactinquiry",
                    name="ad_campaign",
                    field=models.CharField(
                        blank=True, default="", max_length=80, null=True
                    ),
                ),
                migrations.AddField(
                    model_name="contactinquiry",
                    name="ad_group",
                    field=models.CharField(
                        blank=True, default="", max_length=80, null=True
                    ),
                ),
                migrations.AddField(
                    model_name="contactinquiry",
                    name="ad_intent",
                    field=models.CharField(
                        blank=True, default="", max_length=80, null=True
                    ),
                ),
                migrations.AddField(
                    model_name="contactinquiry",
                    name="ad_keyword",
                    field=models.CharField(
                        blank=True, default="", max_length=120, null=True
                    ),
                ),
                migrations.AddField(
                    model_name="contactinquiry",
                    name="ad_source",
                    field=models.CharField(
                        blank=True, default="", max_length=40, null=True
                    ),
                ),
                migrations.AddField(
                    model_name="contactinquiry",
                    name="landing_variant",
                    field=models.CharField(
                        blank=True, default="", max_length=80, null=True
                    ),
                ),
                migrations.AddField(
                    model_name="contactinquiry",
                    name="lead_source",
                    field=models.CharField(
                        blank=True, default="", max_length=80, null=True
                    ),
                ),
                migrations.AddField(
                    model_name="contactinquiry",
                    name="page_key",
                    field=models.CharField(
                        blank=True, default="", max_length=40, null=True
                    ),
                ),
            ],
        ),
    ]
