# Generated by Codex on 2026-06-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0011_contactinquiry_ad_attribution"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "landing_contactinquiry" ADD COLUMN "ad_creative" varchar(80) NULL;',
                    reverse_sql='ALTER TABLE "landing_contactinquiry" DROP COLUMN "ad_creative";',
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="contactinquiry",
                    name="ad_creative",
                    field=models.CharField(
                        blank=True, default="", max_length=80, null=True
                    ),
                ),
            ],
        ),
    ]
